### PR TITLE
Update Hybridauth 3.3 library.

### LINKED ISSUE #3: Add support for Hybridauth 3.x

### PR DESCRIPTION
**Pull request by julionc**
- Follow CodeIgniter's PHP Style Guide.
- Clean up Hybridauth CI Library.
- Fixed Basic controller integration.

Fixes #3 and #7

cc: @ApacheEx

### CODE REVIEW

**Comment by ApacheEx** [comment]
wow, thank you a lot. It looks great. I will release it as new major version.

**Comment by julionc** [comment]
Hi @ApacheEx 
I forget to edit the config file at
https://github.com/ApacheEx/CodeIgniter-HybridAuth/blob/master/application/config/hybridauth.php#L20
It should be `window` in your case.

Kudos to you!

**Comment by ApacheEx** [comment]
I had the same feeling but wasn't sure. Thanks for notice.

**Comment by isantolin** [comment]
@ApacheEx @julionc Anyone can update to CI4?

**Pull request merged**
